// generate random number between 1 and 0
let randomnumber = Math.random();
console.log(randomnumber);


// times the random number generated by 10 to give a number between 1 and 10
randomnumber = randomnumber * 10;
console.log(randomnumber);

// round down to nearest whole number
randomnumber = Math.floor(randomnumber);
console.log(randomnumber);

// adds 1 to make it between 1 and 10 rather than 0 and 9
randomnumber = randomnumber + 1;
console.log(randomnumber);

// does it all on 1 line omg
let randomnumber2 = Math.floor(Math.random() * 10) + 1;
console.log(randomnumber2)

// create variable to store the current date
let d = new Date();
console.log(d);

// create variables to store the day month and year from the d variable
let date = d.getDate();
let month = d.getMonth() + 1;
let year = d.getFullYear();

// create a formatted message
console.log(`Today is ${date}/${month}/${year}, and today I have learnt about JavaScript objects`);


// ask user to enter their dob

let dobYear = prompt("What year were you born? Please enter in the format YYYY");
console.log(dobYear);

let dobMonth = prompt("What month were you born? Answer!!! (MM)")
console.log(dobMonth);

let dobDate = prompt("What Day of the month were you born? Write as DD");
console.log(dobDate);

console.log(`your date of birth is ${dobDate}/${dobMonth}/${dobYear}`);

let dob = new Date(dobYear, dobMonth - 1, dobDate);
console.log(dob);

// calculate difference between current date and date of birth
let ageYears = d.getFullYear() - dob.getFullYear();
console.log(ageYears);

// get current date & month, get dob & month, compare the two to see if the birthdate has passed yet, if the date hasn't passed -1 from the result
if (d.getMonth() < dob.getMonth() || (d.getMonth == dob.getMonth && d.getDate() < dob.getDate())) {
    ageYears--;
}
console.log(ageYears);


let myName = "Josh Robinson";

let nameLength = myName.length;
console.log(`Your name is ${myName} and has ${nameLength} characters.`);

let newName = myName.replace("Josh", "Joe").replace("Robinson", "Bloggs");
console.log(`New name: ${newName}`);

let upperCaseName = myName.toUpperCase();
console.log(upperCaseName);

let dob = prompt("What is your Date of Birth, please give in DD/MM/YYYY format.");
let dobSplit = dob.split('/');

let dobDate = dobSplit[0];
let dobMonth = dobSplit[1];
let dobYear = dobSplit[2];

console.log(`Day: ${dobDate}`);
console.log(`Month: ${dobMonth}`);
console.log(`Year: ${dobYear}`);

